# Generated by Django 5.2.1 on 2025-06-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepro',
            name='descriptions',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
