# Generated by Django 5.2.1 on 2025-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_homepro_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepro',
            name='descriptions',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
