# Generated by Django 5.2.1 on 2025-06-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_homepro_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='mens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=100)),
                ('mimage', models.ImageField(default='/static/images/default.png', upload_to='')),
                ('mprice', models.IntegerField(default=0)),
                ('mdescriptions', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='homepro',
            name='image',
            field=models.ImageField(default='/static/images/default.png', upload_to=''),
        ),
    ]
