# Generated by Django 5.2.1 on 2025-06-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_mens_alter_homepro_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='womens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=100)),
                ('wimage', models.ImageField(default='defult.png', upload_to='')),
                ('wprice', models.IntegerField(default=0)),
                ('wdescriptions', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='homepro',
            name='image',
            field=models.ImageField(default='defult.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='mens',
            name='mdescriptions',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mens',
            name='mimage',
            field=models.ImageField(default='defult.png', upload_to=''),
        ),
    ]
