# Generated by Django 5.2.1 on 2025-07-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_homepro_descriptions_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='desc',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default='defult.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='unnamed', max_length=180),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='q',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_p',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
