# Generated by Django 5.2.1 on 2025-07-05 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_cart_product_remove_cart_quantity_cart_desc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phonenumber', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Gujrat', 'Gujrat'), ('Mumbai', 'Mumbai'), ('Banglore', 'Banglore')], max_length=100)),
                ('zipcode', models.CharField(max_length=6)),
                ('card_num', models.PositiveIntegerField(max_length=16)),
                ('e_date', models.CharField(max_length=4)),
                ('cvv', models.PositiveIntegerField(max_length=3)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
